using System;
using System.Collections.Generic;
using System.Text;

namespace Bibitinator.Models
{
    internal class NeuralNetEditorNodes
    {
        public BibiteReflect.Node[] inputNodesOld = {
            new BibiteReflect.Node { Index = 0, Desc = "Constant", TypeName = "Input", NIn = 0, NOut = 0, Type = 0},
            new BibiteReflect.Node { Index = 1, Desc = "EnergyRatio", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 2, Desc = "Maturity", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 3, Desc = "LifeRatio", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 4, Desc = "Speed", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 5, Desc = "IsGrabbingObjects", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 6, Desc = "AttackDamage", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 7, Desc = "BibiteConcentrationWeight", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 8, Desc = "BibiteConcentrationAngle", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 9, Desc = "NVisibleBibites", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 10, Desc = "PelletConcentrationWeight", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 11, Desc = "PelletConcentrationAngle", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 12, Desc = "NVisiblePellets", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 13, Desc = "MeatConcentrationWeight", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 14, Desc = "MeatConcentrationAngle", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 15, Desc = "NVisibleMeat", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 16, Desc = "ClosestBibiteR", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 17, Desc = "ClosestBibiteG", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 18, Desc = "CloestBibiteB", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 19, Desc = "Tic", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 20, Desc = "Minute", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 21, Desc = "TimeAlive", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 22, Desc = "PheroSense1", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 23, Desc = "PheroSense2", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 24, Desc = "PheroSense3", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 25, Desc = "Phero1Angle", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 26, Desc = "Phero2Angle", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 27, Desc = "Phero3Angle", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 },
            new BibiteReflect.Node { Index = 28, Desc = "InfectionRate", TypeName = "Input", NIn = 0, NOut = 0, Type = 0 }
            };
        public BibiteReflect.Node[] inputNodesNew = {
            new BibiteReflect.Node { Index = 0, Desc = "Constant", TypeName = "Input", Type = 0},
            new BibiteReflect.Node { Index = 1, Desc = "EnergyRatio", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 2, Desc = "Maturity", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 3, Desc = "LifeRatio", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 4, Desc = "Fullness", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 5, Desc = "Speed", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 6, Desc = "IsGrabbingObjects", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 7, Desc = "AttackDamage", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 8, Desc = "BibiteConcentrationWeight", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 9, Desc = "BibiteConcentrationAngle", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 10, Desc = "NVisibleBibites", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 11, Desc = "PelletConcentrationWeight", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 12, Desc = "PelletConcentrationAngle", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 13, Desc = "NVisiblePellets", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 14, Desc = "MeatConcentrationWeight", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 15, Desc = "MeatConcentrationAngle", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 16, Desc = "NVisibleMeat", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 17, Desc = "ClosestBibiteR", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 18, Desc = "ClosestBibiteG", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 19, Desc = "CloestBibiteB", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 20, Desc = "Tic", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 21, Desc = "Minute", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 22, Desc = "TimeAlive", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 23, Desc = "PheroSense1", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 24, Desc = "PheroSense2", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 25, Desc = "PheroSense3", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 26, Desc = "Phero1Angle", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 27, Desc = "Phero2Angle", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 28, Desc = "Phero3Angle", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 29, Desc = "PheroHeading1", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 30, Desc = "PheroHeading2", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 31, Desc = "PheroHeading3", TypeName = "Input", Type = 0 },
            new BibiteReflect.Node { Index = 32, Desc = "InfectionRate", TypeName = "Input", Type = 0 }
            };
        public BibiteReflect.Node[] outputNodesOld = {
            new BibiteReflect.Node { Index = 29, Desc = "Accelerate", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 30, Desc = "Rotate", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 31, Desc = "Herding", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 32, Desc = "Want2Lay", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 33, Desc = "Want2Eat", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 34, Desc = "Want2Sex", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 35, Desc = "Grab", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 36, Desc = "ClkReset", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 37, Desc = "Phere1Out", TypeName = "ReLu", Type = 5, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 38, Desc = "Phere2Out", TypeName = "ReLu", Type = 5, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 39, Desc = "Phere3Out", TypeName = "ReLu", Type = 5, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 40, Desc = "Want2Grow", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 41, Desc = "Want2Heal", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 42, Desc = "Want2Attack", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 43, Desc = "ImmuneSystem", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
        };
        public BibiteReflect.Node[] outputNodesNew = {
            new BibiteReflect.Node { Index = 33, Desc = "Accelerate", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 34, Desc = "Rotate", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 35, Desc = "Herding", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 36, Desc = "Want2Lay", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 37, Desc = "Want2Eat", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 38, Desc = "Want2Sex", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 39, Desc = "Grab", TypeName = "TanH", Type = 3, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 40, Desc = "ClkReset", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 41, Desc = "Phere1Out", TypeName = "ReLu", Type = 5, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 42, Desc = "Phere2Out", TypeName = "ReLu", Type = 5, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 43, Desc = "Phere3Out", TypeName = "ReLu", Type = 5, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 44, Desc = "Want2Grow", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 45, Desc = "Want2Heal", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 46, Desc = "Want2Attack", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
            new BibiteReflect.Node { Index = 47, Desc = "ImmuneSystem", TypeName = "Sigmoid", Type = 1, NIn = 0, NOut = 0},
        };
        public BibiteReflect.Node[] middleNodes ={
            new BibiteReflect.Node { Type = 1, TypeName = "Sigmoid"},
            new BibiteReflect.Node { Type = 2, TypeName = "Linear"},
            new BibiteReflect.Node { Type = 3, TypeName = "TanH"},
            new BibiteReflect.Node { Type = 4, TypeName = "Sine"},
            new BibiteReflect.Node { Type = 5, TypeName = "ReLu"},
            new BibiteReflect.Node { Type = 6, TypeName = "Gaussian"},
            new BibiteReflect.Node { Type = 7, TypeName = "Latch"},
            new BibiteReflect.Node { Type = 8, TypeName = "Differential"},
        };
        public List<BibiteReflect.Node> hiddenNodes = new List<BibiteReflect.Node>();
    }
}
